# Generated by Django 2.2.12 on 2021-06-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('searchquery', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=10)),
                ('dateandtime', models.CharField(max_length=40)),
            ],
        ),
    ]
